version: '3.8'

services:
  web:
    build:
      context: ../
      dockerfile: docker/apache/Dockerfile
    ports:
      - "8000:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    volumes:
      - ../public:/var/www/html
      - ../src:/var/www/src
      - ../vendor:/var/www/vendor
      - ../data:/var/www/html/data
      - ./.env:/var/www/html/.env
    depends_on:
      - db

  db:
    image: mysql:5.6
    container_name: mysql56
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scandiweb_ecommerce
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: