version: '3.8'

services:
  web:
    mem_limit: 512m
    cpus: 1
    build:
      context: ../
      dockerfile: docker/apache/Dockerfile
    ports:
      - "8000:8080"
    environment:
      - PHP_ERROR_REPORTING=E_ALL
      - PHP_DISPLAY_ERRORS=On
      - PHP_LOG_ERRORS=On
      - PHP_ERROR_LOG=/var/log/php_errors.log
      - MYSQL_HOST:mysql-qgkp.railway.internal
      - MYSQL_PORT:3306
      - MYSQL_DATABASE:railway
      - MYSQL_USER=root
      - MYSQL_PASSWORD:hhyqaXpUrzJMBHhoCEddogCNnnaoICJB
    volumes:
    
    - ../.env:/var/www/.env
    - ../public:/var/www/html/public
    - ../src:/var/www/src
    - ../vendor:/var/www/vendor
    - ../data:/var/www/html/data
    env_file:
    - ../.env

    depends_on:
      - db

  db:
    image: mysql:5.6
    container_name: mysql56
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scandiweb_ecommerce
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: