version: '3.8'

services:
  web:
    mem_limit: 512m
    cpus: 1
    build:
      context: ../
      dockerfile: docker/apache/Dockerfile
    ports:
      - "8000:8080"
    environment:
      - PHP_ERROR_REPORTING=E_ALL
      - PHP_DISPLAY_ERRORS=On
      - PHP_LOG_ERRORS=On
      - PHP_ERROR_LOG=/var/log/php_errors.log
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    env_file:
      - ../.env.docker
    volumes:
      - ./.env:/var/www/html/.env
      - ../public:/var/www/html/public
      - ../src:/var/www/src
      - ../vendor:/var/www/vendor
      - ../data:/var/www/html/data
      - ../docker/php.ini:/usr/local/etc/php/php.ini 



    depends_on:
      - db

  db:
    image: mysql:5.6
    container_name: mysql56
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql




volumes:
  db_data: