name: Build and Deploy to GCR

on:
  push:
    branches:
      - main

env:
  GCR_REGISTRY: gcr.io
  PROJECT_ID: ecommerce-backend-454022
  IMAGE_NAME: ${{ lower(github.repository) }}
  IMAGE_TAG: ${{ github.sha }}
  REMOTE_USER: rababrain
  REMOTE_HOST: 104.197.195.13

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GCR
        run: |
          echo "${{ secrets.GCR_CREDENTIALS }}" | docker login -u _json_key --password-stdin https://${{ env.GCR_REGISTRY }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.GCR_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker Image to GCR
        run: |
          docker push ${{ env.GCR_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} "
            docker pull ${{ env.GCR_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} &&
            docker run -d ${{ env.GCR_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
