name: Build and Deploy to GCR

on:
  push:
    branches:
      - master

env:
  GCR_REGISTRY: gcr.io
  PROJECT_ID: ecommerce-backend-454022
  IMAGE_NAME: ecommerce-backend
  IMAGE_TAG: v1
  REMOTE_USER: rababbrain
  REMOTE_HOST: 104.197.195.135

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCR_CREDENTIALS }}
          export_default_credentials: true

      - name: Authenticate Docker with GCR
        run: |
          gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          docker build -f backend/docker/apache/Dockerfile \
            -t ${{ env.GCR_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            backend
      - name: Push Docker Image to GCR
        run: |
          docker push ${{ env.GCR_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} "
            docker pull ${{ env.GCR_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} &&
            docker stop ecommerce-backend || true &&
            docker rm ecommerce-backend || true &&
            docker run -d --name ecommerce-backend -p 8080:8000 ${{ env.GCR_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          "
